services:
  - type: web
    name: billing-app
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --threads 8 --timeout 120 "app:create_app()"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:////opt/render/project/src/database/billing.db
